// category navigations
export const categoryNavigation = [
  {
    icon: "Home",
    title: "Home",
    href: "/product/search/Dariry & Eggs",
  },
  {
    icon: "Popular",
    title: "Popular Products",
    href: "/product/search/Breakfast",
  },
  {
    icon: "Trending",
    title: "Trending Products",
    href: "/product/search/Frozen",
  },
  {
    icon: "Products",
    title: "All Products",
    href: "/product/search/vegetables",
  },
  {
    icon: "HealthBeauty",
    title: "Health and beauty",
    href: "/product/search/Fruits & Vegetables",
    child: [
      {
        title: "Beauty Items",
        href: "/product/search/Onion",
      },
      {
        title: "Medicine Items",
        href: "/product/search/Potato",
      },
      {
        title: "Makeup Items",
        href: "/product/search/Vegetable Pack",
      },
    ],
  },
  {
    icon: "Mascara",
    title: "Mascara",
    href: "/product/search/Dariry & Eggs",
    child: [
      {
        title: "Beauty Items",
        href: "/product/search/Onion",
      },
      {
        title: "Medicine Items",
        href: "/product/search/Potato",
      },
      {
        title: "Makeup Items",
        href: "/product/search/Vegetable Pack",
      },
    ],
  },
  {
    icon: "Powder",
    title: "Powder",
    href: "/product/search/Breakfast",
    child: [
      {
        title: "Beauty Items",
        href: "/product/search/Onion",
      },
      {
        title: "Medicine Items",
        href: "/product/search/Potato",
      },
      {
        title: "Makeup Items",
        href: "/product/search/Vegetable Pack",
      },
    ],
  },
  {
    icon: "Lotion",
    title: "Lotion",
    href: "/product/search/Frozen",
    child: [
      {
        title: "Beauty Items",
        href: "/product/search/Onion",
      },
      {
        title: "Medicine Items",
        href: "/product/search/Potato",
      },
      {
        title: "Makeup Items",
        href: "/product/search/Vegetable Pack",
      },
    ],
  },
  {
    icon: "HealthBeauty",
    title: "Makeup",
    href: "/product/search/Organic",
    child: [
      {
        title: "Beauty Items",
        href: "/product/search/Onion",
      },
      {
        title: "Medicine Items",
        href: "/product/search/Potato",
      },
      {
        title: "Makeup Items",
        href: "/product/search/Vegetable Pack",
      },
    ],
  },
  {
    icon: "Lipstick",
    title: "Lipstick",
    href: "/product/search/Canned Food",
    child: [
      {
        title: "Beauty Items",
        href: "/product/search/Onion",
      },
      {
        title: "Medicine Items",
        href: "/product/search/Potato",
      },
      {
        title: "Makeup Items",
        href: "/product/search/Vegetable Pack",
      },
    ],
  },
  {
    icon: "FaceMask",
    title: "Face Mask",
    href: "/product/search/Coffee & Snacks",
    child: [
      {
        title: "Beauty Items",
        href: "/product/search/Onion",
      },
      {
        title: "Medicine Items",
        href: "/product/search/Potato",
      },
      {
        title: "Makeup Items",
        href: "/product/search/Vegetable Pack",
      },
    ],
  },
  {
    icon: "Thermometer",
    title: "Digital Thermometer",
    href: "/product/search/Sauces & Jems",
  },
  {
    icon: "OxygenPump",
    title: "Oxygen Pump",
    href: "/product/search/Breakfast",
  },
  {
    icon: "LenseCase",
    title: "Lense Case Kit",
    href: "/product/search/Frozen",
  },
  {
    icon: "AutoMotive",
    title: "Automotive",
    href: "/product/search/Organic",
  },
]; // main carousel data

export const mainCarouselData = [
  {
    id: 1,
    href: "/",
    imgUrl: "/assets/congbinh/banners/banner1.jpg",
  },
  {
    id: 2,
    href: "/",
    imgUrl: "/assets/congbinh/banners/banner2.jpg",
  },
  {
    id: 3,
    href: "/",
    imgUrl: "/assets/congbinh/banners/banner3.jpg",
  },
  {
    id: 4,
    href: "/",
    imgUrl: "/assets/congbinh/banners/banner4.jpg",
  },
]; // services

export const serviceList = [
  {
    id: "ad6a361d-9048-49e5-9fa7-927737892857",
    icon: "Truck",
    title: "Giao hàng nhanh",
    description: "Tiết kiệm chi phí",
  },
  {
    id: "2ba74d7d-dfeb-4337-9397-e849572a1244",
    icon: "MoneyGuarantee",
    title: "Bảo hành",
    description: "Từ 1 năm",
  },
  {
    id: "dcea23c6-e735-429c-ac35-5903a938f2f8",
    icon: "OnlineService",
    title: "Hỗ trợ",
    description: "24/7",
  },
  {
    id: "ecea23c6-e735-429c-ac35-5903a938f2f7",
    icon: "Payment",
    title: "Thanh toán",
    description: "Tiện lợi",
  },
]; // products

export const products = [
  {
    id: "0897bb87-e229-4d39-8639-c451ef57d1cf",
    slug: "vichy-liftactiv-nuit-cream",
    shop: {
      id: "8e28ee3c-7c2c-4e6a-a274-cdf4d1c13243",
      slug: "constant-shoppers",
      user: {
        id: "9c820520-32ee-4683-9925-d0e7e22945d0",
        email: "Minnie_Muller@yahoo.com",
        phone: "572.422.3075",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/598.jpg",
        password: "vUrcT43mZb0pKZB",
        dateOfBirth: "1984-11-13T13:17:09.709Z",
        verified: true,
        name: {
          firstName: "Brayan",
          lastName: "Bahringer",
        },
      },
      email: "Easter_Farrell@hotmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Máy Chụp X-quang Đứng Lifedent",
    brand: null,
    price: 189,
    size: null,
    colors: [],
    discount: 8,
    thumbnail: "/assets/congbinh/products/product1.jpg",
    images: [
      "/assets/congbinh/products/product1.jpg",
      "/assets/congbinh/products/product1.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "health-beauty",
      type: "top-new-products",
    },
  },
  {
    id: "9c34f12c-927a-42df-8b4c-990084c8c1aa",
    slug: "blue-stethoscope",
    shop: {
      id: "7171ab4e-1fbf-45b6-95d9-07cf9ed386be",
      slug: "cybershop",
      user: {
        id: "0f6dbcd1-cbe3-4e4f-a04c-41228ff1b3c9",
        email: "Bertram_OKeefe@yahoo.com",
        phone: "963.267.5451 x31173",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/204.jpg",
        password: "7KyZDbburluaiPK",
        dateOfBirth: "1944-12-20T14:46:49.006Z",
        verified: true,
        name: {
          firstName: "Roger",
          lastName: "Wolff",
        },
      },
      email: "Abel24@yahoo.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Xquang cầm tay Le Ray G",
    brand: null,
    price: 165,
    size: null,
    colors: [],
    discount: 9,
    thumbnail: "/assets/congbinh/products/product2.jpg",
    images: [
      "/assets/congbinh/products/product2.jpg",
      "/assets/congbinh/products/product2.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "health-beauty",
      type: "top-new-products",
    },
  },
  {
    id: "55012664-65c3-469c-b079-f309a4d38a32",
    slug: "sphygmomanometer",
    shop: {
      id: "2807d7cb-e6d9-4d0b-8812-1cc4df3f9c21",
      slug: "scroll-through",
      user: {
        id: "b6a3cc46-8c32-4587-b198-28129ee663ca",
        email: "Manuel27@gmail.com",
        phone: "991.950.6385 x327",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/659.jpg",
        password: "HybgISkBPngysfY",
        dateOfBirth: "1951-01-10T16:01:46.055Z",
        verified: true,
        name: {
          firstName: "Karlie",
          lastName: "Lubowitz",
        },
      },
      email: "Marisol86@hotmail.com",
      name: "Scroll Through",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner.png",
      profilePicture: "/assets/images/faces/propic(1).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Ghế nha khoa chân inox hàn",
    brand: null,
    price: 72,
    size: null,
    colors: [],
    discount: 12,
    thumbnail: "/assets/congbinh/products/product3.jpg",
    images: [
      "/assets/congbinh/products/product3.jpg",
      "/assets/congbinh/products/product3.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "health-beauty",
      type: "top-new-products",
    },
  },
  {
    id: "fb05df26-d62c-4900-8204-08e972e67bd0",
    slug: "vichy-liftactiv-cream",
    shop: {
      id: "8e28ee3c-7c2c-4e6a-a274-cdf4d1c13243",
      slug: "constant-shoppers",
      user: {
        id: "9c820520-32ee-4683-9925-d0e7e22945d0",
        email: "Minnie_Muller@yahoo.com",
        phone: "572.422.3075",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/598.jpg",
        password: "vUrcT43mZb0pKZB",
        dateOfBirth: "1984-11-13T13:17:09.709Z",
        verified: true,
        name: {
          firstName: "Brayan",
          lastName: "Bahringer",
        },
      },
      email: "Easter_Farrell@hotmail.com",
      name: "Constant Shoppers",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-4.png",
      profilePicture: "/assets/images/faces/propic(3).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Xquang Cầm Tay Le Ray P",
    brand: null,
    price: 163,
    size: null,
    colors: [],
    discount: 7,
    thumbnail: "/assets/congbinh/products/product4.jpg",
    images: [
      "/assets/congbinh/products/product4.jpg",
      "/assets/congbinh/products/product4.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "health-beauty",
      type: "top-new-products",
    },
  },
  {
    id: "51f780bb-76ae-4220-87ec-f483f19927d1",
    slug: "nivea-cream-soft-milk",
    shop: {
      id: "d007aa7b-4b37-4638-8725-2fbac11c9ba2",
      slug: "scarlett-beauty",
      user: {
        id: "e7f0ca46-bbb6-4f4f-aa53-03314c5cd4ca",
        email: "Trevor.Wiegand@yahoo.com",
        phone: "448-827-4111 x4838",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/501.jpg",
        password: "56HwcpES9tYkRM1",
        dateOfBirth: "1994-02-19T22:26:16.913Z",
        verified: true,
        name: {
          firstName: "Selena",
          lastName: "Bauch",
        },
      },
      email: "Rebeca.Batz@gmail.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-9.png",
      profilePicture: "/assets/images/faces/propic(8).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Máy lấy cao răng bình nước rời, 2 trong 1",
    brand: null,
    price: 180,
    size: null,
    colors: [],
    discount: 8,
    thumbnail: "/assets/congbinh/products/product5.jpg",
    images: [
      "/assets/congbinh/products/product5.jpg",
      "/assets/congbinh/products/product5.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "health-beauty",
      type: "top-new-products",
    },
  },
  {
    id: "0cf0efe4-5df3-43a8-ab14-03d2c22bc511",
    slug: "vichy-liftactiv-nuit-cream",
    shop: {
      id: "e230d1b7-ce69-464c-a891-4e02ecd7a1c7",
      slug: "anytime-buys",
      user: {
        id: "216acb7f-ba3c-43c2-85c1-97a5128bc6ae",
        email: "Gerry82@hotmail.com",
        phone: "(480) 527-7250 x21254",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/861.jpg",
        password: "0c200xIHZ_lT69W",
        dateOfBirth: "1983-06-19T09:40:00.964Z",
        verified: true,
        name: {
          firstName: "Ashly",
          lastName: "Jacobs",
        },
      },
      email: "Rodger43@hotmail.com",
      name: "Anytime Buys",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-6.png",
      profilePicture: "/assets/images/faces/propic(5).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Máy Chụp X-quang Đứng Lifedent",
    brand: null,
    price: 230,
    size: null,
    colors: [],
    discount: 8,
    thumbnail: "/assets/congbinh/products/product6.jpg",
    images: [
      "/assets/congbinh/products/product6.jpg",
      "/assets/congbinh/products/product6.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "health-beauty",
      type: "all-products",
    },
  },
  {
    id: "484341ff-0df8-403d-a96f-55bff4b05f2c",
    slug: "sphygmomanometer",
    shop: {
      id: "f2520e47-8896-453a-974c-68feb7179d82",
      slug: "coveted-clicks",
      user: {
        id: "78714862-d7de-4f3a-b980-d1860e8705b1",
        email: "Luther.Dietrich89@hotmail.com",
        phone: "1-531-939-7384 x886",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/557.jpg",
        password: "ja1RIwEewiuvMvw",
        dateOfBirth: "1979-07-03T15:19:12.594Z",
        verified: true,
        name: {
          firstName: "Kamryn",
          lastName: "Quigley",
        },
      },
      email: "Myron_Trantow60@hotmail.com",
      name: "Coveted Clicks",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-3.png",
      profilePicture: "/assets/images/faces/propic(2).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Máy nội nha Endo Motor có đèn",
    brand: null,
    price: 65,
    size: null,
    colors: [],
    discount: 6,
    thumbnail: "/assets/congbinh/products/product7.jpg",
    images: [
      "/assets/congbinh/products/product7.jpg",
      "/assets/congbinh/products/product7.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "health-beauty",
      type: "all-products",
    },
  },
  {
    id: "d1ecaafe-1311-4ed9-881c-eed23d4666c0",
    slug: "fresh-strawberry",
    shop: {
      id: "820fa522-81ed-43a0-85c9-11d7d7c37739",
      slug: "cybershop",
      user: {
        id: "e4453cb5-00ab-4f21-849e-f889fc55fbea",
        email: "Clair_Hessel95@gmail.com",
        phone: "1-277-251-0731",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1051.jpg",
        password: "lXXPcbS0vW3bAfV",
        dateOfBirth: "1982-07-25T17:38:03.396Z",
        verified: true,
        name: {
          firstName: "Harold",
          lastName: "Ortiz",
        },
      },
      email: "Claud92@hotmail.com",
      name: "Cybershop",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-8.png",
      profilePicture: "/assets/images/faces/propic(7).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Máy nội nha tích hợp định vị chóp Duote (tặng 3 vỉ file)",
    brand: null,
    price: 181,
    size: null,
    colors: [],
    discount: 11,
    thumbnail: "/assets/congbinh/products/product8.jpg",
    images: [
      "/assets/congbinh/products/product8.jpg",
      "/assets/congbinh/products/product8.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "health-beauty",
      type: "all-products",
    },
  },
  {
    id: "c4358795-6d87-448e-a88a-3ceccb2a8fa4",
    slug: "nivea-cream",
    shop: {
      id: "01286864-9cc2-4586-b327-3da85658a3dc",
      slug: "scroll-through",
      user: {
        id: "bc47fc7b-6762-4e3d-9ffb-30f1799db6d1",
        email: "Nina_Ledner10@hotmail.com",
        phone: "1-426-360-3744",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1108.jpg",
        password: "yVQy480bQMVnCl2",
        dateOfBirth: "1966-08-17T05:08:58.542Z",
        verified: true,
        name: {
          firstName: "Kirk",
          lastName: "Morissette",
        },
      },
      email: "Jade_Stark@yahoo.com",
      name: "Scroll Through",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner.png",
      profilePicture: "/assets/images/faces/propic(1).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Pin Xquang cầm tay Le Ray P",
    brand: null,
    price: 211,
    size: null,
    colors: [],
    discount: 11,
    thumbnail: "/assets/congbinh/products/product9.jpg",
    images: [
      "/assets/congbinh/products/product9.jpg",
      "/assets/congbinh/products/product9.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 4,
    for: {
      demo: "health-beauty",
      type: "all-products",
    },
  },
  {
    id: "c2716a69-3972-4f71-8800-ad61898fd0fb",
    slug: "vichy-liftactiv-nuit-cream",
    shop: {
      id: "005e180a-42b2-44ad-a38b-e42bbdde0587",
      slug: "scarlett-beauty",
      user: {
        id: "94d05f5e-696f-43dc-b61d-d6282d00a272",
        email: "Karl2@hotmail.com",
        phone: "281-617-8345 x55859",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/203.jpg",
        password: "WiQlpVUlxSF9Rid",
        dateOfBirth: "1977-03-08T15:12:48.293Z",
        verified: true,
        name: {
          firstName: "Otilia",
          lastName: "Schaefer",
        },
      },
      email: "Lina.Bosco51@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-9.png",
      profilePicture: "/assets/images/faces/propic(8).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Giá để máy lấy cao",
    brand: null,
    price: 189,
    size: null,
    colors: [],
    discount: 8,
    thumbnail: "/assets/congbinh/products/product10.jpg",
    images: [
      "/assets/congbinh/products/product10.jpg",
      "/assets/congbinh/products/product10.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 5,
    for: {
      demo: "health-beauty",
      type: "all-products",
    },
  },
  {
    id: "cfb75612-ddb5-4680-9029-c59ffefa2087",
    slug: "blue-stethoscope",
    shop: {
      id: "c97bd8ca-2fe3-4781-b43c-6b441a071499",
      slug: "word-wide-wishes",
      user: {
        id: "d725ba5f-5571-40ba-b8b2-b77547cf7e39",
        email: "Edythe_Sauer37@hotmail.com",
        phone: "(499) 284-4740 x6909",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/660.jpg",
        password: "zjzzl_46e03B3FP",
        dateOfBirth: "1997-06-07T17:14:16.460Z",
        verified: true,
        name: {
          firstName: "Gabriella",
          lastName: "Kreiger",
        },
      },
      email: "Percival_McCullough@gmail.com",
      name: "Word Wide Wishes",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner-7.png",
      profilePicture: "/assets/images/faces/propic(6).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    title: "Van điện 30v máy lấy cao",
    brand: null,
    price: 165,
    size: null,
    colors: [],
    discount: 9,
    thumbnail: "/assets/congbinh/products/product11.jpg",
    images: [
      "/assets/congbinh/products/product11.jpg",
      "/assets/congbinh/products/product11.jpg",
    ],
    categories: ["healthbeauty"],
    status: null,
    reviews: [],
    rating: 3,
    for: {
      demo: "health-beauty",
      type: "all-products",
    },
  },
];

export const categories = [
  {
    iconSrc: "/assets/congbinh/categories/icon-ghe-nha.png",
    title: "Ghế nha khoa",
    href: "/fashion",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-chinh-nha.png",
    title: "Máy lấy cao răng",
    href: "/product/search/electronics",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-tay-khoan-nha-khoa.png",
    title: "Tay khoan nha khoa",
    href: "/product/search/bikes",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-thiet-bi-chup-x-quang.png",
    title: "Thiết bị chụp X-Quang, Camera",
    href: "/product/search/home&garden",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-den-tram-leb.png",
    title: "Đèn trám led",
    href: "/product/search/music",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-noi-nha.png",
    title: "Nội nha, định vị chóp",
    href: "/product/search/health&beauty",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-nha-chu-phau-thuat.png",
    title: "Nha nhu, phẫu thuật",
    href: "/product/search/pets",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-ve-sinh-vo-trung.png",
    title: "Thiết bị tiệt trùng",
    href: "/product/search/groceries",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-digital-imaging.png",
    title: "Sensor nha khoa",
    href: "/product/search/automotive",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-nha-khoa-phuc-hoi.png",
    title: "Linh kiện, vật tư, thiết bị nhỏ",
    href: "/product/search/automotive",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-labo.png",
    title: "Máy nén khí không dầu",
    href: "/product/search/automotive",
  },
  {
    iconSrc: "/assets/congbinh/categories/icon-labo.png",
    title: "Máy hút trung tâm",
    href: "/product/search/automotive",
  },
];

export const testimonialList = [
  {
    rating: 5,
    id: "aa95e3fd-c170-431a-b9cd-abaac45a048f",
    user: {
      name: "Nguyễn Văn A",
      avatar: "/assets/images/faces/4.jpg",
    },
    comment: `Công cụ nha khoa chất lượng, giao hàng đúng hẹn và miễn phí vận chuyển. Mình rất hài lòng và sẽ tiếp tục mua sắm ở đây!`,
  },
  {
    rating: 5,
    id: "72c79d90-abc7-467d-b7b2-e94905a9e18a",
    user: {
      name: "Nguyễn Văn B",
      avatar: "/assets/images/faces/12.jpg",
    },
    comment: `Rất hài lòng với sản phẩm và dịch vụ chuyên nghiệp! Công cụ nha khoa giao đúng hẹn, không mất phí vận chuyển. Sản phẩm bền, dễ sử dụng, sẽ ủng hộ lần sau!`,
  },
  {
    rating: 5,
    id: "fc39e3b3-de7b-4ffa-aa64-63ca0c21c5c8",
    user: {
      name: "Nguyễn Văn C",
      avatar: "/assets/images/faces/7.png",
    },
    comment: `Sản phẩm chất lượng, giao hàng nhanh chóng và miễn phí vận chuyển. Rất hài lòng với sự chuyên nghiệp, chắc chắn sẽ tiếp tục ủng hộ!`,
  },
]; // get all products

export const brands = [
  {
    id: "9aee1898-23e0-4965-8f0d-427dc963ae07",
    slug: "alibaba",
    name: "AliBaba",
    image: "/assets/congbinh/brands/brand1.jpg",
  },
  {
    id: "024ec2a2-7ca7-46c2-8990-f78ac4215dd1",
    slug: "levis",
    name: "Levis",
    image: "/assets/congbinh/brands/brand2.jpg",
  },
  {
    id: "e370f16a-90e2-4f26-b9af-a38d6f645a4c",
    slug: "lotto",
    name: "Lotto",
    image: "/assets/congbinh/brands/brand3.jpg",
  },
  {
    id: "d8f4c60e-6bac-4fdc-9880-999fbddac97d",
    slug: "raymond",
    name: "Raymond",
    image: "/assets/congbinh/brands/brand4.jpg",
  },
  {
    id: "0c74cb7c-6082-4640-9380-815928be7127",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/congbinh/brands/brand5.jpg",
  },
  {
    id: "0c74cb7c-6082-4640-9380-815928be7124",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/congbinh/brands/brand6.jpg",
  },
  {
    id: "0c74cb7c-6082-4640-9380-815928be7427",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/congbinh/brands/brand7.jpg",
  },
  {
    id: "0c74cb7c-6082-4640-9380-815928be3127",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/congbinh/brands/brand8.jpg",
  },
  {
    id: "0c74cb7c-6082-4640-9380-815928be3157",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/congbinh/brands/brand9.jpg",
  },
  {
    id: "0c74cb7c-6082-4640-9380-815922be3157",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/congbinh/brands/brand10.jpg",
  },
  {
    id: "0c74cb7c-6082-4640-9380-815922bf3157",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/congbinh/brands/brand11.jpg",
  },
  {
    id: "0c74cb7c-6082-4640-9330-815922bf3157",
    slug: "samsung",
    name: "Samsung",
    image: "/assets/congbinh/brands/brand12.jpg",
  },
];

export const blogs = [
  {
    id: "20a83049-bc4b-41cc-9a29-0b2b69a7fd08",
    title: "Tìm hiểu các phân khúc ghế nha khoa",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit.…",
    thumbnail: "/assets/congbinh/blogs/blog1.jpg",
    shop: {
      id: "e7c5030b-0504-4b4c-81dc-1627302bc1a4",
      slug: "scarlett-beauty",
      user: {
        id: "642f50d7-944b-459e-aa20-154afdccb413",
        email: "Annette_Gleason@yahoo.com",
        phone: "(607) 973-2857 x445",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/435.jpg",
        password: "C_mhvNPAeAU7Mj4",
        dateOfBirth: "1963-06-10T22:22:55.842Z",
        verified: true,
        name: {
          firstName: "Rosa",
          lastName: "Pagac",
        },
      },
      email: "Isabella.Kris13@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    user: {
      id: "642f50d7-944b-459e-aa20-154afdccb413",
      email: "Annette_Gleason@yahoo.com",
      phone: "(607) 973-2857 x445",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/435.jpg",
      password: "C_mhvNPAeAU7Mj4",
      dateOfBirth: "1963-06-10T22:22:55.842Z",
      verified: true,
      name: {
        firstName: "Rosa",
        lastName: "Pagac",
      },
    },
    createdAt: "21 SEP",
    slug: "30percent-off-coupon-for-black-friday",
  },
  {
    id: "108015ad-897b-4c90-a90f-53b288ad162c",
    title: "Ghế nha khoa SUNTEM ST-D580",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit.…",
    thumbnail: "/assets/congbinh/blogs/blog2.jpg",
    shop: {
      id: "d32b469e-4ccc-43b4-8427-98eba478355f",
      slug: "scroll-through",
      user: {
        id: "992c82b5-8a64-47a3-b665-2b59b6f950e6",
        email: "Enid99@yahoo.com",
        phone: "(672) 865-8949",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/759.jpg",
        password: "ZlNtd6J9UV37Enm",
        dateOfBirth: "1951-03-01T08:56:59.687Z",
        verified: true,
        name: {
          firstName: "Oren",
          lastName: "Pagac",
        },
      },
      email: "Cheyanne.Kutch56@gmail.com",
      name: "Scroll Through",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/banner.png",
      profilePicture: "/assets/images/faces/propic(1).png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    user: {
      id: "bd8b4e8b-6794-42f3-a42f-a2abd903ced9",
      email: "Alexa.Dickens65@yahoo.com",
      phone: "1-904-617-0268 x6023",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/965.jpg",
      password: "PxqJTybdKi_Qrcb",
      dateOfBirth: "1959-12-13T23:47:11.023Z",
      verified: true,
      name: {
        firstName: "Jamar",
        lastName: "Kuhn",
      },
    },
    createdAt: "21 SEP",
    slug: "10percent-discount-for-cosmatics",
  },
  {
    id: "f3f920ba-3f3e-47cd-a109-9183a15479fa",
    title: "Đau mỏi khớp thái dương",
    description:
      "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Phasellus hendrerit.…",
    thumbnail: "/assets/congbinh/blogs/blog3.jpg",
    shop: {
      id: "e7c5030b-0504-4b4c-81dc-1627302bc1a4",
      slug: "scarlett-beauty",
      user: {
        id: "642f50d7-944b-459e-aa20-154afdccb413",
        email: "Annette_Gleason@yahoo.com",
        phone: "(607) 973-2857 x445",
        avatar:
          "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/435.jpg",
        password: "C_mhvNPAeAU7Mj4",
        dateOfBirth: "1963-06-10T22:22:55.842Z",
        verified: true,
        name: {
          firstName: "Rosa",
          lastName: "Pagac",
        },
      },
      email: "Isabella.Kris13@yahoo.com",
      name: "Scarlett Beauty",
      phone: "(613) 343-9004",
      address: "845 N. Stonybrook Ave. Tonawanda, NY 14210, Denmark",
      verified: false,
      coverPicture: "/assets/images/banners/cycle.png",
      profilePicture: "/assets/images/faces/propic.png",
      socialLinks: {
        facebook: null,
        youtube: null,
        twitter: null,
        instagram: null,
      },
    },
    user: {
      id: "642f50d7-944b-459e-aa20-154afdccb413",
      email: "Annette_Gleason@yahoo.com",
      phone: "(607) 973-2857 x445",
      avatar:
        "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/435.jpg",
      password: "C_mhvNPAeAU7Mj4",
      dateOfBirth: "1963-06-10T22:22:55.842Z",
      verified: true,
      name: {
        firstName: "Rosa",
        lastName: "Pagac",
      },
    },
    createdAt: "21 SEP",
    slug: "buy-2-get-1-free-offer",
  },
];
